name: Apply pip compile (generate lockfiles)

on: workflow_dispatch

jobs:
  apply-pip-compile:
    name: Apply pip compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "python_version=$(python3 scripts/get_python_version.py)" >> "$GITHUB_OUTPUT"
        id: get-python-version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.get-python-version.outputs.python_version }}
      - name: Install uv
        run: |
          pip3 install uv
      - name: Run uv pip compile and push
        run: |
          set +e  # Do not exit shell on failure
          bash scripts/compile_requirements.sh
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "build: update requirements using uv pip compile [skip ci]"
          git push
