name: Commit CHANGELOG.md, create a Release and deploy MkDocs

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: New version tag that starts with 'v' (e.g. v0.1.0)
        required: true
        default: v0.1.0
      dry-run:
        description: Show a sample changelog in Summary without committing or creating a release
        type: boolean
        default: false

jobs:
  commit-changelog-and-release:
    uses: deargen/workflows/.github/workflows/commit-changelog-and-release.yml@master
    with:
      version-tag: ${{ github.event.inputs.version-tag }}
      dry-run: ${{ github.event.inputs.dry-run }}
      changelog-path: docs/CHANGELOG.md
      exclude-types: build,docs,style,other

  deploy-mkdocs:
    needs: commit-changelog-and-release
    uses: deargen/workflows/.github/workflows/deploy-mkdocs.yml@master
    with:
      requirements-file: deps/x86_64-unknown-linux-gnu/requirements_docs.txt
      gitlab-project: ${{ vars.GITLAB_PROJECT }}
      gitlab-branch: gl-pages
      version-tag: ${{ github.event.inputs.version-tag }}
      deploy-type: tag
    secrets:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
