name: Style checking

on: [push, pull_request]

jobs:
  ruff-format:
    name: ruff-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install ruff
        run: |
          pip3 install ruff==0.1.14
      - name: Run ruff format
        run: |
          set +e  # Do not exit shell on black failure
          out=$(ruff format --check --diff . 2> app_stderr.txt)
          exit_code=$?
          err=$(<app_stderr.txt)

          # Display the raw output in the step
          echo "${out}"
          echo "${err}"

          # Display the Markdown output in the job summary
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          echo "${out}" >> $GITHUB_STEP_SUMMARY
          echo "${err}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          # Exit with the exit-code returned by ruff
          exit ${exit_code}

  ruff-isort:
    name: ruff-isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install ruff
        run: |
          pip3 install ruff==0.1.14
      - name: Run ruff isort
        run: |
          set +e  # Do not exit shell on app failure
          out=$(ruff --select I --diff . 2> app_stderr.txt)
          exit_code=$?
          err=$(<app_stderr.txt)

          # Display the raw output in the step
          echo "${out}"
          echo "${err}"

          # Display the Markdown output in the job summary
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          echo "${out}" >> $GITHUB_STEP_SUMMARY
          echo "${err}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          # Exit with the exit-code returned by ruff
          exit ${exit_code}
