name: Type checking

on:
  push:
    branches:
      - main
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  basedpyright:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python and uv
        uses: deargen/workflows/actions/setup-python-and-uv@master
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install basedpyright
          uv pip install -r deps/lock/x86_64-manylinux_2_28/requirements_dev.txt
          uv pip install -e .[dev]
      - name: Type checking
        run: |
          source .venv/bin/activate
          basedpyright
